### PR TITLE
Fix incorrect filename in exercise 2

### PR DESCRIPTION
**Pull request by degeens**
In the markdown file of exercise 2 there is a reference to 'src/examples/hook-flow.png' while the file is called '02-hook-flow.png'.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Actually could you instead rename the file?

Thanks!

**Comment by degeens** [comment]
> Actually could you instead rename the file?
> 
> Thanks!

Sure, done! 😉

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @degeens for docs

**Pull request merged**
