### PR TITLE
satelite favicon for simple hooks

### PR DESCRIPTION
**Pull request by Aprillion**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks! Could we do this one instead?

02-react-hooks

**Comment by kentcdodds** [comment]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @Aprillion for code

**Comment by aishaaljahani** [comment]
I am new in GitHub But I see  your project and I like it and then I try to
see it form my phon so I press bottom maybe it was accident

If you can explain what I’m did to send massage to my email because I’m
don’t understand what GitHub

في أحد، ٤ أكتوبر، ٢٠٢٠ في ٥:٥٧ ص، كتب allcontributors[bot] <
notifications@github.com>:

**Comment by kentcdodds** [comment]
@aishaaljahani, you are "watching" this repo: https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions

**Pull request merged**
