### PR TITLE
fix: the address of the Pokemon api has moved

### PR DESCRIPTION
**Pull request by dschapman**
- https://graphql-pokemon.now.sh/ is no longer available and has been moved to https://graphql-pokemon2.vercel.app/

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks for this! I'm actually cool to accept this PR, but we'll want to change our MSW handlers as well: https://github.com/kentcdodds/react-hooks/blob/master/src/backend.js

I want this repo to work completely offline, which is why we have MSW in place to handle this :)

**Comment by dschapman** [comment]
I fixed the link in backend.js are there any other changes that need to be made?

**Review by kentcdodds — APPROVED** [review]
Super, thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @dschapman for code

**Pull request merged**
