### PR TITLE
Update 04.md - minor text update

### PR DESCRIPTION
**Pull request by heypano**
Official docs [no longer use classes for the tic tac toe example](https://react.dev/learn/tutorial-tic-tac-toe)

### CODE REVIEW

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Thanks for this! Could you update the PR to not include your changes in the `.js`?

**Comment by heypano** [comment]
> Thanks for this! Could you update the PR to not include your changes in the `.js`?

oops! sorry about that @kentcdodds  -- updated!

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @heypano for docs

**Pull request merged**
